# Generated by Django 4.0.3 on 2022-11-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "tmdb_id",
                    models.PositiveSmallIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "tmdb_id",
                    models.PositiveSmallIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("runtime", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="movies", to="movies_app.genre"
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
