# Generated by Django 4.0.3 on 2022-09-09 00:58
# Backup in case migration files are deleted.

from django.db import migrations


def load_initial_data(apps, schema_editor):
    genre_model = apps.get_model("movies_app", "Genre")
    genres = [
        {"name": "Action", "tmdb_id": 28},
        {"name": "Adventure", "tmdb_id": 12},
        {"name": "Animation", "tmdb_id": 16},
        {"name": "Comedy", "tmdb_id": 35},
        {"name": "Crime", "tmdb_id": 80},
        {"name": "Documentary", "tmdb_id": 99},
        {"name": "Drama", "tmdb_id": 18},
        {"name": "Family", "tmdb_id": 10751},
        {"name": "Fantasy", "tmdb_id": 14},
        {"name": "History", "tmdb_id": 36},
        {"name": "Horror", "tmdb_id": 27},
        {"name": "Music", "tmdb_id": 10402},
        {"name": "Mystery", "tmdb_id": 9648},
        {"name": "Romance", "tmdb_id": 10749},
        {"name": "Science Fiction", "tmdb_id": 878},
        {"name": "TV Movie", "tmdb_id": 10770},
        {"name": "Thriller", "tmdb_id": 53},
        {"name": "War", "tmdb_id": 10752},
        {"name": "Western", "tmdb_id": 37},
    ]
    for genre in genres:
        genre_model.objects.create(name=genre["name"], tmdb_id=genre["tmdb_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
