# Generated by Django 4.0.3 on 2022-12-09 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrating",
            name="score",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
    ]
