# syntax=docker/dockerfile:1

FROM python:3.10-bullseye
ENV PYTHONBUFFERED 1
RUN python -m pip install --upgrade pip
WORKDIR /deps
COPY requirements.txt requirements.txt
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
RUN python -m pip install -r requirements.txt
WORKDIR /app
CMD [ "python3", "-m" , "flask", "--debug", "run", "--host=0.0.0.0"]
